version: 0.0
os: linux

files:
  - source: target/case-yellow-central.jar
    destination: /home/ec2-user/case-yellow
  - source: scripts/esoteric
    destination: /home/ec2-user/case-yellow/scripts

permissions:
  - object: /home/ec2-user/case-yellow/scripts
    pattern: "**"
    mode: 777
    group: ec2-user
    owner: ec2-user
    type:
      - file
  - object: /home/ec2-user/case-yellow
    pattern: "*scripts*"
    owner: ec2-user
    mode: 777
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/delete_app_binary.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/stop_app_process.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_app_process.sh
      timeout: 120
      runas: ec2-user