version: 0.0
os: linux

files:
  - source: target/case-yellow-central.jar
    destination: /home/ec2-user/case-yellow
  - source: scripts/esoteric
    destination: /home/ec2-user/case-yellow/scripts

permissions:
  - object: /home/ec2-user/case-yellow/scripts
    mode: 644
    acls:
      - "d:u::rwx"
      - "d:g::rwx"
      - "d:o::rwx"
    owner: ec2-user
    type:
      - directory

hooks:
  BeforeInstall:
    - location: scripts/delete_app_binary.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/stop_app_process.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start_app_process.sh
      timeout: 120
      runas: ec2-user