# Server Port
server.port : 9080

# Profiles
spring.profiles.active: prod

# FileDownloadService properties
num_of_comparison_per_test: 3

# Flyway
flyway.baseline-on-migrate: true

# Elastic Search
es_enable: false

# misc
successful_tests_dir: successful-tests/
run.extra.identifiers: false

# Files Download Properties
fileDownloadProperties:
 firefox:
  identifier: firefox
  url: https://ftp.mozilla.org/pub/firefox/releases/37.0b1/win32/en-US/Firefox%20Setup%2037.0b1.exe
  size: 40797024
  md5: 6F8E20894953F5ABD8809F645DA9A791

 go:
  identifier: go
  url: https://storage.googleapis.com/golang/go1.7.1.windows-amd64.msi
  size: 75001856
  md5: 39F8A2B6F62B5E8E4268076EC5DFD9B0

 amazon-workSpaces:
  identifier: amazon-workSpaces
  url: https://d2td7dqidlhjx7.cloudfront.net/prod/global/windows/Amazon+WorkSpaces.msi
  size: 43139072
  md5: 68941C8D6519949A04B8148B2783628F

 my-sql:
  identifier: my-sql
  url: https://dev.mysql.com/get/Downloads/MySQLInstaller/mysql-installer-web-community-5.7.20.0.msi
  size: 19443712
  md5: D5316E440206EB0FD9F32CFFF37CD132

 windows-games-studio:
  identifier: windows-games-studio
  url: https://download.microsoft.com/download/0/1/4/01483A18-289E-4779-BB5A-0A28DFE18BC5/XNAGS40_setup.exe
  size: 51182360
  md5: D8CEBEDDA6BF24CE43B0F2B7A1475C96

 dlink :
  identifier: dlink
  url: https://www.bezeq.co.il/media/249421/DWA-160.exe
  size: 15277856
  md5: 524CC1D0FBC90949F1849362F65BAAC3

 quicktime:
  identifier: quicktime
  url: https://secure-appldnld.apple.com/QuickTime/031-43075-20160107-C0844134-B3CD-11E5-B1C0-43CA8D551951/QuickTimeInstaller.exe
  size: 41896256
  md5: 1A762049BEF7FC3A53014833757DE2D2

speedTestUrls:
 bezeq: http://www.bezeq.co.il/internetandphone/internet/speedtest/
 fast: https://www.fast.com/
 hot: http://www.hot.net.il/heb/Internet/speed/
 ookla: http://beta.speedtest.net/
 google: http://speedtest.googlefiber.net/

speedTest:
  extraIdentifiers:
    - hot
    - ookla
  chromeOptionsArguments:
    - "--allow-outdated-plugins"
    - "--disable-features=EnableEphemeralFlashPermission"
    - "disable-infobars"

aws:
  regions:
    frankfurt: eu-central-1
    ireland: eu-west-1
    north-california: us-west-1
#    sydney: ap-southeast-2
#    tokyo: ap-northeast-1


connection-details:
  speed:
    - 15
    - 30
    - 40
    - 100
    - 200
    - 500
    - 1000

  infrastructure:
    - HOT
    - BEZEQ
    - UNLIMITED
    - PARTNER


# Logger
log.dir: /home/ec2-user/case-yellow/logs

logging:
  level:
    org.springframework.web: ERROR
    caseyellow.server.gateway: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - [%X{correlation-id}] - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - [%X{correlation-id}] - %m%n"
  file: ${log.dir}/caseyellow-central-log