#Postgres source
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://caseyellow.cgqzew4kdsmr.eu-central-1.rds.amazonaws.com:5432/caseyellow
spring.datasource.username: dango
spring.datasource.password: ${DATASOURCE_PASSWORD}

spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update

# SQS
sqs.queue.endpoint: https://sqs.eu-central-1.amazonaws.com
sqs.central.queue: cy-central-queue

# mail service
email.username: caseyellow22@gmail.com

emails:
  - name: dan
    email: dangolan24@gmail.com
    role: admin
  - name: oren
    email: koriatoren@gmail.com
    role: admin
  - name: ori
    email: oriamitay82@gmail.com
    role: lawyer
  - name: rom
    email: romamit@gmail.com
    role: preacher
