# Postgres
spring.datasource.driverClassName: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://caseyellow.cgqzew4kdsmr.eu-central-1.rds.amazonaws.com:5432/caseyellow
spring.datasource.username: dango
spring.datasource.password: ${DATASOURCE_PASSWORD}

# JPA
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.javax.persistence.query.timeout: 600000

# SQS
sqs.queue.endpoint: https://sqs.eu-central-1.amazonaws.com
sqs.central.queue: cy-central-queue
sqs.image_analyze.queue: cy-image-analysis

# DynamoDB
dynamo.endpoint: https://dynamodb.eu-central-1.amazonaws.com
dynamo.region: eu-central-1
dynamo.user.statistics.table.name: cy_user_statistics

#?
encryption_key: nokey

# Email service
email.username: caseyellow22@gmail.com

emails:
  - name: dan
    email: dangolan24@gmail.com
    role: admin
  - name: oren
    email: koriatoren@gmail.com
    role: admin
  - name: ori
    email: oriamitay82@gmail.com
    role: lawyer
  - name: rom
    email: romamit@gmail.com
    role: preacher
