#Postgres database
spring.datasource.url: jdbc:postgresql://case-yellow.cgqzew4kdsmr.eu-central-1.rds.amazonaws.com:5432/case_yellow
spring.datasource.username: dango
spring.datasource.password: Jackbauer24

spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update