server.port : 8888
config:
  app-name: Gateway
  app-description: ${app-name} is the the handler from user requests
  admin-first-name: Dan
  admin-last-name: Golan
  admin-mail: caseyellow22@gmail.com