# Server Port
server.port : 9080

# Profiles
spring.profiles.active: prod

# MultiPart properties
spring.http.multipart.max-file-size: 5MB
spring.http.multipart.max-request-size: 20MB

# Services
analysis_url: http://localhost:8088/analysis/

# Logger
log.dir: /home/ec2-user/case-yellow-central

logging:
  level:
    org.springframework.web: ERROR
    caseyellow.server.gateway: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] - %-5p %c{1}:%L - %m%n"
  file: ${log.dir}/logs/case_yellow_central_log.log

fileDownloadUrls:
 firefox: https://ftp.mozilla.org/pub/firefox/releases/37.0b1/win32/en-US/Firefox%20Setup%2037.0b1.exe
 go: https://storage.googleapis.com/golang/go1.7.1.windows-amd64.msi
 java-sdk: https://sdk-for-java.amazonwebservices.com/latest/aws-java-sdk.zip
 postgres: https://get.enterprisedb.com/postgresql/postgresql-10.0-1-windows-x64.exe
 kinect: https://download.microsoft.com/download/F/2/D/F2D1012E-3BC6-49C5-B8B3-5ACFF58AF7B8/KinectSDK-v2.0_1409-Setup.exe
 itunes: https://secure-appldnld.apple.com/itunes12/031-69284-20160802-7E7B2D20-552B-11E6-B2B9-696CECD541CE/iTunes64Setup.exe

speedTestUrls :
 atnt: http://speedtest.att.com/speedtest/
 bezeq: http://www.bezeq.co.il/internetandphone/internet/speedtest/
 fast: https://www.fast.com/
 hot: http://www.hot.net.il/heb/Internet/speed/
 ookla: http://beta.speedtest.net/
 speedof: http://www.speedof.me/

nonFlashIdentifiers:
 - atnt
 - fast
 - speedof


